import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AudioContextProvider } from "@/context/CostumeAudioContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Birthday Cake",
  description: "Generated by Jadde Suarez",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AudioContextProvider>
        <body className={inter.className}>{children}</body>
      </AudioContextProvider>
    </html>
  );
}
